[project]
name = 'welsh-street'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.credit-controller]
path = 'contracts/credit-controller.clar'
clarity_version = 3
epoch = 'latest'

[contracts.credit-token]
path = 'contracts/credit-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.faucet]
path = 'contracts/faucet.clar'
clarity_version = 3
epoch = 'latest'

[contracts.genesis]
path = 'contracts/genesis.clar'
clarity_version = 3
epoch = 'latest'

[contracts.street-market]
path = 'contracts/street-market.clar'
clarity_version = 3
epoch = 'latest'

[contracts.street-rewards]
path = 'contracts/street-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.street-token]
path = 'contracts/street-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.welshcorgicoin]
path = 'contracts/welshcorgicoin.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['call_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.testnet.hiro.so'
